import 'package:vehicle_rental/models/car_model.dart';

List<Car> getCarList() {
  return <Car>[
    Car(
      'Innova Reborn',
      'Toyota',
      'assets/car/innova_reborn.png',
      85000,
      'Gray',
      'Automatic',
      '6',
      'Diesel',
      '146,9'
    ),
    Car(
      'Almaz',
      'Wuling',
      'assets/car/almaz.png',
      60000,
      'Red',
      'Automatic',
      '6',
      'Petrol',
      '140'
    ),
    Car(
      'HR-V',
      'Honda',
      'assets/car/hrv.png',
      100000,
      'Brown',
      'Automatic',
      '4',
      'Petrol',
      '175'
    ),
    Car(
      'IONIQ 5',
      'Hyundai',
      'assets/car/ioniq5.png',
      200000,
      'White',
      'Automatic',
      '4',
      'Electricity',
      '214'
    ),
    Car(
      'Avanza',
      'Toyota',
      'assets/car/avanza.png',
      50000,
      'Silver',
      'Automatic',
      '6',
      'Petrol',
      '103'
    ),
    Car(
      'Yaris',
      'Toyota',
      'assets/car/yaris.png',
      55000,
      'White',
      'Automatic',
      '4',
      'Petrol',
      '106'
    ),
    Car(
      'Creta',
      'Hyundai',
      'assets/car/creta.png',
      95000,
      'Red',
      'Automatic',
      '4',
      'Petrol',
      '113'
    ),
    Car(
      'Agya',
      'Toyota',
      'assets/car/agya.png',
      52000,
      'White',
      'Automatic',
      '4',
      'Petrol',
      '88'
    ),
    Car(
      'Ayla',
      'Daihatsu',
      'assets/car/ayla.png',
      40000,
      'Yellow',
      'Automatic',
      '4',
      'Petrol',
      '66'
    ),
    Car(
      'Calya',
      'Toyota',
      'assets/car/calya.png',
      45000,
      'White',
      'Automatic',
      '4',
      'Petrol',
      '88'
    ),
    Car(
      'Alphard',
      'Toyota',
      'assets/car/alphard.png',
      300000,
      'White',
      'Automatic',
      '6',
      'Petrol',
      '250'
    ),
    Car(
      'Pajero',
      'Mitsubishi',
      'assets/car/pajero.png',
      160000,
      'White',
      'Automatic',
      '6',
      'Petrol',
      '181'
    ),
    Car(
      'Fortuner',
      'Toyota',
      'assets/car/fortuner.png',
      170000,
      'Black',
      'Automatic',
      '6',
      'Petrol',
      '204'
    ),
    Car(
      'Palisade',
      'Hyundai',
      'assets/car/palisade.png',
      190000,
      'White',
      'Automatic',
      '6',
      'Diesel',
      '200'
    ),
    Car(
      'Santafe',
      'Hyundai',
      'assets/car/santafe.png',
      130000,
      'Black',
      'Automatic',
      '6',
      'Petrol',
      '202'
    ),
  ];
}
